# Generated by Django 4.1.1 on 2022-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotelname', models.CharField(default='', max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('catego', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(upload_to='documents/')),
                ('timi', models.CharField(default='', max_length=100)),
                ('tagline', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
