# Generated by Django 4.1.1 on 2022-11-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hositality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname1', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('item1', models.ImageField(upload_to='documents/')),
                ('ititle', models.CharField(max_length=10)),
                ('iprice', models.CharField(max_length=100)),
            ],
        ),
    ]
