# Generated by Django 4.1.1 on 2022-11-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hositality', '0002_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hositality.hotels'),
        ),
    ]
