# Generated by Django 4.1.1 on 2022-12-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hositality', '0003_items_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='catego',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='ititle',
            field=models.CharField(max_length=100),
        ),
    ]
