# Generated by Django 4.1.1 on 2022-12-02 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hositality', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinein',
            fields=[
                ('hname', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='documents/')),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('Timings', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iprice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hositality.dinein')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
