# Generated by Django 4.1.1 on 2022-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hositality', '0012_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
