# Generated by Django 4.1.1 on 2022-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hositality', '0016_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
    ]
